### ISSUE TITLE
Create a dropdown with the options for domain

### ISSUE THREAD

**Issue by bishaladhikari** [bishaladhikari/job_scraper#1]
### Task Description
Add a dropdown
ae.indeed.com
linkedin.com
gulftalent.com

 ### Before
https://job-scraper-35fd5.web.app/search-result?title=&loc=&keywords=&search=true
### After implementing the feature
https://job-scraper-35fd5.web.app/search-result?domain=ae.indeed.com&title=&loc=&keywords=&search=true

### What to do
 - [ ] add a dropdown with label and value (ae.indeed.com,linkedin.com, gulftalent.com)
 - [ ] submit an api request to the backend and fetch results
 - [ ] the API request should have domain as get paramenter
